// W0-17 build: bundle NearNow for Cloudflare Workers with esbuild.
// 1) generate dist-cloudflare/assets.gen.js (embedded data + web assets)
// 2) esbuild src/worker.ts -> dist-cloudflare/worker.js (node:fs aliased to
//    deploy/fs-shim.mts; other node:* stay external for nodejs_compat)
// 3) print raw + gzip sizes (W0-17 gate: gzip <= 1MB)
import { build } from 'esbuild';
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { gzipSync } from 'node:zlib';
import { pathToFileURL, resolve } from 'node:url';
import { dirname, join } from 'node:path';

const root = dirname(dirname(pathToFileURL(import.meta.url).pathname.replace(/^\/([A-Za-z]:)/, '$1')));

const TEXT_FILES = [
  'data/chain-hours.json',
  'data/geocode-seed.json',
  'data/prompts.json',
  'data/snapshot/manifest.json',
  'data/snapshot/california.jsonl',
  'data/snapshot/texas.jsonl',
  'data/snapshot/new-york.jsonl',
  'web/index.html',
  'web/privacy.html',
  'web/terms.html',
  'web/favicon.svg',
];
const BIN_FILES = ['web/icon-512.png'];

mkdirSync('dist-cloudflare', { recursive: true });

const TEXT = {};
for (const f of TEXT_FILES) TEXT[f] = readFileSync(f, 'utf8');
const BIN = {};
for (const f of BIN_FILES) BIN[f] = readFileSync(f).toString('hex');

const assets = `// GENERATED by deploy/build.mjs — do not edit.\n` +
  `export const TEXT = ${JSON.stringify(TEXT)};\n` +
  `export const BIN = ${JSON.stringify(BIN)};\n`;
writeFileSync('dist-cloudflare/assets.gen.js', assets);

await build({
  entryPoints: ['src/worker.ts'],
  bundle: true,
  format: 'esm',
  platform: 'neutral',
  mainFields: ['main'],
  target: 'es2022',
  minify: true,
  outfile: 'dist-cloudflare/worker.js',
  external: ['node:*'],
  alias: { 'node:fs': './deploy/fs-shim.mts', 'node:url': './deploy/url-shim.mts' },
  logLevel: 'info',
});

const js = readFileSync('dist-cloudflare/worker.js');
const gz = gzipSync(js, { level: 9 });
console.log(`worker.js raw  = ${(js.length / 1024).toFixed(0)} KiB`);
console.log(`worker.js gzip = ${(gz.length / 1024).toFixed(0)} KiB  (gate: <= 1024 KiB)`);
console.log(gz.length <= 1024 * 1024 ? 'SIZE GATE: PASS' : 'SIZE GATE: FAIL -> slim or Render fallback');
